### ISSUE TITLE
Add a Dockerfile to create a container for backend application

### ISSUE THREAD

**Issue by mcruzdev** [mcruzdev/free-programming-ebooks#17]
Create a Dockerfile packaging the SpringBoot application inside a container.

**Comment by ujwalkumar1995** [comment]
Hey @mcruzdev.
Are you just looking to containerize the backend application by copying the jar files inside the docker container and exposing the port?
Or it something extra you are looking for here?

**Comment by mcruzdev** [comment]
Hello @ujwalkumar1995,

Yes, just it... should be simple!

After we will add GithubActions.

**Comment by mcruzdev** [comment]
The result should be the backend application running into container

**Comment by mcruzdev** [comment]
Closed by #21
