### ISSUE TITLE
Create an admin page to register an Ebook

### ISSUE THREAD

**Issue by mcruzdev** [mcruzdev/free-programming-ebooks#18]
We need a page to register a ebook.

An Ebook has:

Name - string
Link - string
Image - File

The `name` is the ebook's name
The `link`is a OneDrive link by example
The `image` is an ebook's image

Use [material](https://mui.com/) components to do it :)

**The backend is not ready yet, focus only in UI components!**

**Comment by mcruzdev** [comment]
The ebook admin page should look something like this…

![admin](https://user-images.githubusercontent.com/56329339/194373625-6430f04a-965a-46e8-90cc-387c7fceec07.png)

**Comment by ygcorrea** [comment]
Hey @mcruzdev i can work on this. Can you assign me plaease?

**Comment by mcruzdev** [comment]
Yes! thank you!
