### ISSUE TITLE
Define the palette color as variables

### ISSUE THREAD

**Issue by mcruzdev** [mcruzdev/free-programming-ebooks#7]
We need to create some variables to define the palette colors to use it on the project on the future.

Create a SASS file called variables.scss with follows values:

![palette](https://user-images.githubusercontent.com/56329339/194145718-8de62e52-d3e5-4a9d-af7b-79b1932f0184.png)

**Comment by P-DR0ZD** [comment]
@mcruzdev Can I be assigned to this? and do I put this in the Styles Directory?
