### ISSUE TITLE
Create navbar component to home page

### ISSUE THREAD

**Issue by mcruzdev** [mcruzdev/free-programming-ebooks#9]
We need to add a new component ( navbar ) to main page.

The backgroud color should be `#274156 `navy-blue' (See variables.scss file)

Should contains a brand: Free programming ebooks on left side

**Comment by Gulshan-11** [comment]
Hey @mcruzdev assign this to me i can work on this

**Comment by michelcalisto** [comment]
open more issues!

**Comment by mcruzdev** [comment]
> Hey @mcruzdev assign this to me i can work on this


Sorry,  but @ygcorrea already started the implementation.

@ygcorrea comment here before start the implementation, thank you!

**Comment by mcruzdev** [comment]
@ygcorrea, 

Can you add material components? https://mui.com/ 

Will be nice if you add a ThemeProvider, if necessary you can change the setting of variables.

**Comment by ygcorrea** [comment]
@mcruzdev sure! i'm adding it!
